// web/js/components/jqwidgets/jqwidgets-react/react_jqxgauge.js
/*
jQWidgets v4.5.0 (2017-Jan)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxGauge = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['animationDuration','border','caption','cap','colorScheme','disabled','easing','endAngle','height','int64','labels','min','max','pointer','radius','ranges','startAngle','showRanges','style','ticksMajor','ticksMinor','ticksDistance','value','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxGauge(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxGauge('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxGauge(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  animationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("animationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("animationDuration");
    }
  },
  border: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("border", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("border");
    }
  },
  caption: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("caption", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("caption");
    }
  },
  cap: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("cap", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("cap");
    }
  },
  colorScheme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("colorScheme", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("colorScheme");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("disabled");
    }
  },
  easing: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("easing", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("easing");
    }
  },
  endAngle: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("endAngle", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("endAngle");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("height");
    }
  },
  int64: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("int64", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("int64");
    }
  },
  labels: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("labels", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("labels");
    }
  },
  min: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("min", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("min");
    }
  },
  max: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("max", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("max");
    }
  },
  pointer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("pointer", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("pointer");
    }
  },
  radius: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("radius", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("radius");
    }
  },
  ranges: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("ranges", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("ranges");
    }
  },
  startAngle: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("startAngle", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("startAngle");
    }
  },
  showRanges: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("showRanges", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("showRanges");
    }
  },
  style: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("style", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("style");
    }
  },
  ticksMajor: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("ticksMajor", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("ticksMajor");
    }
  },
  ticksMinor: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("ticksMinor", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("ticksMinor");
    }
  },
  ticksDistance: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("ticksDistance", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("ticksDistance");
    }
  },
  value: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("value", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("value");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxGauge("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxGauge("width");
    }
  },
  disable: function () {
    $("#" +this.componentSelector).jqxGauge("disable");  
  },
  enable: function () {
    $("#" +this.componentSelector).jqxGauge("enable");  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" +this.componentSelector).jqxGauge("val", value)
    } else {
      return $("#" +this.componentSelector).jqxGauge("val");
    }
  },

  render: function () {
    let id = 'jqxGauge' + this.generateID() + this.generateID();
    this.componentSelector = id;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxGauge;

// web/js/components/jqwidgets/jqwidgets-ts/angular_jqxgauge.ts
/*
jQWidgets v4.5.0 (2017-Jan)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxGauge',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxGaugeComponent implements OnChanges
{
   @Input('animationDuration') attrAnimationDuration: any;
   @Input('border') attrBorder: any;
   @Input('caption') attrCaption: any;
   @Input('cap') attrCap: any;
   @Input('colorScheme') attrColorScheme: any;
   @Input('disabled') attrDisabled: any;
   @Input('easing') attrEasing: any;
   @Input('endAngle') attrEndAngle: any;
   @Input('int64') attrInt64: any;
   @Input('labels') attrLabels: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('pointer') attrPointer: any;
   @Input('radius') attrRadius: any;
   @Input('ranges') attrRanges: any;
   @Input('startAngle') attrStartAngle: any;
   @Input('showRanges') attrShowRanges: any;
   @Input('style') attrStyle: any;
   @Input('ticksMajor') attrTicksMajor: any;
   @Input('ticksMinor') attrTicksMinor: any;
   @Input('ticksDistance') attrTicksDistance: any;
   @Input('value') attrValue: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['animationDuration','border','caption','cap','colorScheme','disabled','easing','endAngle','height','int64','labels','min','max','pointer','radius','ranges','startAngle','showRanges','style','ticksMajor','ticksMinor','ticksDistance','value','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxGauge;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxGauge(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxGauge(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxGauge(this.properties[i])) {
                  this.host.jqxGauge(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxGauge', options);
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({width: this.attrWidth, height: this.attrHeight});
   }

   setOptions(options: any) : void {
      this.host.jqxGauge('setOptions', options);
   }

   // jqxGaugeComponent properties
   animationDuration(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('animationDuration', arg);
      } else {
          return this.host.jqxGauge('animationDuration');
      }
   }

   border(arg?: jqwidgets.GaugeBorder) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('border', arg);
      } else {
          return this.host.jqxGauge('border');
      }
   }

   caption(arg?: jqwidgets.GaugeCaption) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('caption', arg);
      } else {
          return this.host.jqxGauge('caption');
      }
   }

   cap(arg?: jqwidgets.GaugeCap) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('cap', arg);
      } else {
          return this.host.jqxGauge('cap');
      }
   }

   colorScheme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('colorScheme', arg);
      } else {
          return this.host.jqxGauge('colorScheme');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('disabled', arg);
      } else {
          return this.host.jqxGauge('disabled');
      }
   }

   easing(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('easing', arg);
      } else {
          return this.host.jqxGauge('easing');
      }
   }

   endAngle(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('endAngle', arg);
      } else {
          return this.host.jqxGauge('endAngle');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('height', arg);
      } else {
          return this.host.jqxGauge('height');
      }
   }

   int64(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('int64', arg);
      } else {
          return this.host.jqxGauge('int64');
      }
   }

   labels(arg?: jqwidgets.GaugeLabels) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('labels', arg);
      } else {
          return this.host.jqxGauge('labels');
      }
   }

   min(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('min', arg);
      } else {
          return this.host.jqxGauge('min');
      }
   }

   max(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('max', arg);
      } else {
          return this.host.jqxGauge('max');
      }
   }

   pointer(arg?: jqwidgets.GaugePointer) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('pointer', arg);
      } else {
          return this.host.jqxGauge('pointer');
      }
   }

   radius(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('radius', arg);
      } else {
          return this.host.jqxGauge('radius');
      }
   }

   ranges(arg?: Array<jqwidgets.GaugeRanges>) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('ranges', arg);
      } else {
          return this.host.jqxGauge('ranges');
      }
   }

   startAngle(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('startAngle', arg);
      } else {
          return this.host.jqxGauge('startAngle');
      }
   }

   showRanges(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('showRanges', arg);
      } else {
          return this.host.jqxGauge('showRanges');
      }
   }

   style(arg?: jqwidgets.GaugeStyle) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('style', arg);
      } else {
          return this.host.jqxGauge('style');
      }
   }

   ticksMajor(arg?: jqwidgets.GaugeTicks) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('ticksMajor', arg);
      } else {
          return this.host.jqxGauge('ticksMajor');
      }
   }

   ticksMinor(arg?: jqwidgets.GaugeTicks) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('ticksMinor', arg);
      } else {
          return this.host.jqxGauge('ticksMinor');
      }
   }

   ticksDistance(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('ticksDistance', arg);
      } else {
          return this.host.jqxGauge('ticksDistance');
      }
   }

   value(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('value', arg);
      } else {
          return this.host.jqxGauge('value');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxGauge('width', arg);
      } else {
          return this.host.jqxGauge('width');
      }
   }


   // jqxGaugeComponent functions
   disable(): void {
      this.host.jqxGauge('disable');
   }

   enable(): void {
      this.host.jqxGauge('enable');
   }

   val(arg?: String | Number): any {
      if (arg !== undefined) {
         this.host.jqxGauge("val", arg);
      } else {
         return this.host.jqxGauge("val");
      }
   };


   // jqxGaugeComponent events
   @Output() onValueChanging = new EventEmitter();
   @Output() onValueChanged = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('valueChanging', (eventData: any) => { this.onValueChanging.emit(eventData); });
      this.host.on('valueChanged', (eventData: any) => { this.onValueChanged.emit(eventData); });
   }

} //jqxGaugeComponent
