// web/js/components/jqwidgets/jqwidgets-react/react_jqxnumberinput.js
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxNumberInput = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['allowNull','decimal','disabled','decimalDigits','decimalSeparator','digits','groupSeparator','groupSize','height','inputMode','min','max','negativeSymbol','placeHolder','promptChar','rtl','readOnly','spinMode','spinButtons','spinButtonsWidth','spinButtonsStep','symbol','symbolPosition','textAlign','template','theme','value','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxNumberInput(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxNumberInput('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxNumberInput(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  allowNull: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("allowNull", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("allowNull");
    }
  },
  decimal: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("decimal", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("decimal");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("disabled");
    }
  },
  decimalDigits: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("decimalDigits", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("decimalDigits");
    }
  },
  decimalSeparator: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("decimalSeparator", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("decimalSeparator");
    }
  },
  digits: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("digits", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("digits");
    }
  },
  groupSeparator: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("groupSeparator", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("groupSeparator");
    }
  },
  groupSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("groupSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("groupSize");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("height");
    }
  },
  inputMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("inputMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("inputMode");
    }
  },
  min: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("min", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("min");
    }
  },
  max: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("max", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("max");
    }
  },
  negativeSymbol: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("negativeSymbol", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("negativeSymbol");
    }
  },
  placeHolder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("placeHolder", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("placeHolder");
    }
  },
  promptChar: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("promptChar", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("promptChar");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("rtl");
    }
  },
  readOnly: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("readOnly", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("readOnly");
    }
  },
  spinMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("spinMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("spinMode");
    }
  },
  spinButtons: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("spinButtons", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("spinButtons");
    }
  },
  spinButtonsWidth: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("spinButtonsWidth", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("spinButtonsWidth");
    }
  },
  spinButtonsStep: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("spinButtonsStep", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("spinButtonsStep");
    }
  },
  symbol: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("symbol", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("symbol");
    }
  },
  symbolPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("symbolPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("symbolPosition");
    }
  },
  textAlign: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("textAlign", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("textAlign");
    }
  },
  template: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("template", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("template");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("theme");
    }
  },
  value: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("value", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("value");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNumberInput("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxNumberInput("width");
    }
  },
  clear: function () {
    $("#" + this.componentSelector).jqxNumberInput("clear");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxNumberInput("destroy");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxNumberInput("focus");  
  },
  getDecimal: function () {
    return $("#" + this.componentSelector).jqxNumberInput("getDecimal");  
  },
  setDecimal: function (index) {
    $("#" + this.componentSelector).jqxNumberInput("setDecimal", index);  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxNumberInput("val", value)
    } else {
      return $("#" + this.componentSelector).jqxNumberInput("val");
    }
  },

  render: function () {
    var id = 'jqxNumberInput' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}></div>
    )
  }
});

module.exports = jqxNumberInput;

// web/js/components/jqwidgets/jqwidgets-ts/angular_jqxnumberinput.ts
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let $: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxNumberInputComponent),
    multi: true
}

@Component({
    selector: 'jqxNumberInput',
    template: '<input>',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})

export class jqxNumberInputComponent implements ControlValueAccessor, OnChanges 
{
   @Input('allowNull') attrAllowNull: any;
   @Input('decimal') attrDecimal: any;
   @Input('disabled') attrDisabled: any;
   @Input('decimalDigits') attrDecimalDigits: any;
   @Input('decimalSeparator') attrDecimalSeparator: any;
   @Input('digits') attrDigits: any;
   @Input('groupSeparator') attrGroupSeparator: any;
   @Input('groupSize') attrGroupSize: any;
   @Input('inputMode') attrInputMode: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('negativeSymbol') attrNegativeSymbol: any;
   @Input('placeHolder') attrPlaceHolder: any;
   @Input('promptChar') attrPromptChar: any;
   @Input('rtl') attrRtl: any;
   @Input('readOnly') attrReadOnly: any;
   @Input('spinMode') attrSpinMode: any;
   @Input('spinButtons') attrSpinButtons: any;
   @Input('spinButtonsWidth') attrSpinButtonsWidth: any;
   @Input('spinButtonsStep') attrSpinButtonsStep: any;
   @Input('symbol') attrSymbol: any;
   @Input('symbolPosition') attrSymbolPosition: any;
   @Input('textAlign') attrTextAlign: any;
   @Input('template') attrTemplate: any;
   @Input('theme') attrTheme: any;
   @Input('value') attrValue: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['allowNull','decimal','disabled','decimalDigits','decimalSeparator','digits','groupSeparator','groupSize','height','inputMode','min','max','negativeSymbol','placeHolder','promptChar','rtl','readOnly','spinMode','spinButtons','spinButtonsWidth','spinButtonsStep','symbol','symbolPosition','textAlign','template','theme','value','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxNumberInput;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxNumberInput(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxNumberInput(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxNumberInput(this.properties[i])) {
                  this.host.jqxNumberInput(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxNumberInput', options);
      this.host = this.widgetObject['host'];
      this.__wireEvents__();
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.host.jqxNumberInput('val', value);
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxNumberInput('setOptions', options);
   }

   // jqxNumberInputComponent properties
   allowNull(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('allowNull', arg);
      } else {
          return this.host.jqxNumberInput('allowNull');
      }
   }

   decimal(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('decimal', arg);
      } else {
          return this.host.jqxNumberInput('decimal');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('disabled', arg);
      } else {
          return this.host.jqxNumberInput('disabled');
      }
   }

   decimalDigits(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('decimalDigits', arg);
      } else {
          return this.host.jqxNumberInput('decimalDigits');
      }
   }

   decimalSeparator(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('decimalSeparator', arg);
      } else {
          return this.host.jqxNumberInput('decimalSeparator');
      }
   }

   digits(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('digits', arg);
      } else {
          return this.host.jqxNumberInput('digits');
      }
   }

   groupSeparator(arg?: String) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('groupSeparator', arg);
      } else {
          return this.host.jqxNumberInput('groupSeparator');
      }
   }

   groupSize(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('groupSize', arg);
      } else {
          return this.host.jqxNumberInput('groupSize');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('height', arg);
      } else {
          return this.host.jqxNumberInput('height');
      }
   }

   inputMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('inputMode', arg);
      } else {
          return this.host.jqxNumberInput('inputMode');
      }
   }

   min(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('min', arg);
      } else {
          return this.host.jqxNumberInput('min');
      }
   }

   max(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('max', arg);
      } else {
          return this.host.jqxNumberInput('max');
      }
   }

   negativeSymbol(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('negativeSymbol', arg);
      } else {
          return this.host.jqxNumberInput('negativeSymbol');
      }
   }

   placeHolder(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('placeHolder', arg);
      } else {
          return this.host.jqxNumberInput('placeHolder');
      }
   }

   promptChar(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('promptChar', arg);
      } else {
          return this.host.jqxNumberInput('promptChar');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('rtl', arg);
      } else {
          return this.host.jqxNumberInput('rtl');
      }
   }

   readOnly(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('readOnly', arg);
      } else {
          return this.host.jqxNumberInput('readOnly');
      }
   }

   spinMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('spinMode', arg);
      } else {
          return this.host.jqxNumberInput('spinMode');
      }
   }

   spinButtons(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('spinButtons', arg);
      } else {
          return this.host.jqxNumberInput('spinButtons');
      }
   }

   spinButtonsWidth(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('spinButtonsWidth', arg);
      } else {
          return this.host.jqxNumberInput('spinButtonsWidth');
      }
   }

   spinButtonsStep(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('spinButtonsStep', arg);
      } else {
          return this.host.jqxNumberInput('spinButtonsStep');
      }
   }

   symbol(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('symbol', arg);
      } else {
          return this.host.jqxNumberInput('symbol');
      }
   }

   symbolPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('symbolPosition', arg);
      } else {
          return this.host.jqxNumberInput('symbolPosition');
      }
   }

   textAlign(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('textAlign', arg);
      } else {
          return this.host.jqxNumberInput('textAlign');
      }
   }

   template(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('template', arg);
      } else {
          return this.host.jqxNumberInput('template');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('theme', arg);
      } else {
          return this.host.jqxNumberInput('theme');
      }
   }

   value(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('value', arg);
      } else {
          return this.host.jqxNumberInput('value');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNumberInput('width', arg);
      } else {
          return this.host.jqxNumberInput('width');
      }
   }


   // jqxNumberInputComponent functions
   clear(): void {
      this.host.jqxNumberInput('clear');
   }

   destroy(): void {
      this.host.jqxNumberInput('destroy');
   }

   focus(): void {
      this.host.jqxNumberInput('focus');
   }

   getDecimal(): number {
      return this.host.jqxNumberInput('getDecimal');
   }

   setDecimal(index: String | Number): void {
      this.host.jqxNumberInput('setDecimal', index);
   }

   val(value): any {
      if (value !== undefined) {
         this.host.jqxNumberInput("val", value);
      } else {
         return this.host.jqxNumberInput("val");
      }
   };


   // jqxNumberInputComponent events
   @Output() onChange = new EventEmitter();
   @Output() onTextchanged = new EventEmitter();
   @Output() onValueChanged = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); if (eventData.args) this.onChangeCallback(eventData.args.text); });
      this.host.on('textchanged', (eventData: any) => { this.onTextchanged.emit(eventData); if (eventData.args) this.onChangeCallback(eventData.args.text); });
      this.host.on('valueChanged', (eventData: any) => { this.onValueChanged.emit(eventData); if (eventData.args) this.onChangeCallback(eventData.args.text); });
   }

} //jqxNumberInputComponent
