// web/js/components/jqwidgets/jqwidgets-react/react_jqxdatetimeinput.js
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxDateTimeInput = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['animationType','allowNullDate','allowKeyboardDelete','clearString','culture','closeDelay','closeCalendarAfterSelection','dropDownHorizontalAlignment','dropDownVerticalAlignment','disabled','enableBrowserBoundsDetection','enableAbsoluteSelection','firstDayOfWeek','formatString','height','min','max','openDelay','placeHolder','popupZIndex','rtl','readonly','showFooter','selectionMode','showWeekNumbers','showTimeButton','showCalendarButton','theme','template','textAlign','todayString','value','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxDateTimeInput(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxDateTimeInput('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxDateTimeInput(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  animationType: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("animationType", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("animationType");
    }
  },
  allowNullDate: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("allowNullDate", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("allowNullDate");
    }
  },
  allowKeyboardDelete: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("allowKeyboardDelete", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("allowKeyboardDelete");
    }
  },
  clearString: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("clearString", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("clearString");
    }
  },
  culture: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("culture", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("culture");
    }
  },
  closeDelay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("closeDelay", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("closeDelay");
    }
  },
  closeCalendarAfterSelection: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("closeCalendarAfterSelection", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("closeCalendarAfterSelection");
    }
  },
  dropDownHorizontalAlignment: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("dropDownHorizontalAlignment", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("dropDownHorizontalAlignment");
    }
  },
  dropDownVerticalAlignment: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("dropDownVerticalAlignment", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("dropDownVerticalAlignment");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("disabled");
    }
  },
  enableBrowserBoundsDetection: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("enableBrowserBoundsDetection", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("enableBrowserBoundsDetection");
    }
  },
  enableAbsoluteSelection: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("enableAbsoluteSelection", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("enableAbsoluteSelection");
    }
  },
  firstDayOfWeek: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("firstDayOfWeek", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("firstDayOfWeek");
    }
  },
  formatString: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("formatString", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("formatString");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("height");
    }
  },
  min: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("min", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("min");
    }
  },
  max: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("max", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("max");
    }
  },
  openDelay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("openDelay", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("openDelay");
    }
  },
  placeHolder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("placeHolder", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("placeHolder");
    }
  },
  popupZIndex: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("popupZIndex", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("popupZIndex");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("rtl");
    }
  },
  readonly: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("readonly", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("readonly");
    }
  },
  showFooter: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("showFooter", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("showFooter");
    }
  },
  selectionMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("selectionMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("selectionMode");
    }
  },
  showWeekNumbers: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("showWeekNumbers", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("showWeekNumbers");
    }
  },
  showTimeButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("showTimeButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("showTimeButton");
    }
  },
  showCalendarButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("showCalendarButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("showCalendarButton");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("theme");
    }
  },
  template: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("template", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("template");
    }
  },
  textAlign: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("textAlign", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("textAlign");
    }
  },
  todayString: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("todayString", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("todayString");
    }
  },
  value: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("value", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("value");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxDateTimeInput("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxDateTimeInput("width");
    }
  },
  close: function () {
    $("#" + this.componentSelector).jqxDateTimeInput("close");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxDateTimeInput("destroy");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxDateTimeInput("focus");  
  },
  getRange: function (date) {
    return $("#" + this.componentSelector).jqxDateTimeInput("getRange", date);  
  },
  getText: function () {
    return $("#" + this.componentSelector).jqxDateTimeInput("getText");  
  },
  getDate: function () {
    return $("#" + this.componentSelector).jqxDateTimeInput("getDate");  
  },
  getMaxDate: function () {
    return $("#" + this.componentSelector).jqxDateTimeInput("getMaxDate");  
  },
  getMinDate: function () {
    return $("#" + this.componentSelector).jqxDateTimeInput("getMinDate");  
  },
  open: function () {
    $("#" + this.componentSelector).jqxDateTimeInput("open");  
  },
  setRange: function (date, date2) {
    $("#" + this.componentSelector).jqxDateTimeInput("setRange", date, date2);  
  },
  setMinDate: function (date) {
    $("#" + this.componentSelector).jqxDateTimeInput("setMinDate", date);  
  },
  setMaxDate: function (date) {
    $("#" + this.componentSelector).jqxDateTimeInput("setMaxDate", date);  
  },
  setDate: function (date) {
    $("#" + this.componentSelector).jqxDateTimeInput("setDate", date);  
  },
  val: function (value, value2) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxDateTimeInput("val", value, value2)
    } else {
      return $("#" + this.componentSelector).jqxDateTimeInput("val");
    }
  },

  render: function () {
    var id = 'jqxDateTimeInput' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxDateTimeInput;

// web/js/components/jqwidgets/jqwidgets-ts/angular_jqxdatetimeinput.ts
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let $: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxDateTimeInputComponent),
    multi: true
}

@Component({
    selector: 'jqxDateTimeInput',
    template: '<input [(ngModel)]="ngValue">',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})

export class jqxDateTimeInputComponent implements ControlValueAccessor, OnChanges 
{
   @Input('animationType') attrAnimationType: any;
   @Input('allowNullDate') attrAllowNullDate: any;
   @Input('allowKeyboardDelete') attrAllowKeyboardDelete: any;
   @Input('clearString') attrClearString: any;
   @Input('culture') attrCulture: any;
   @Input('closeDelay') attrCloseDelay: any;
   @Input('closeCalendarAfterSelection') attrCloseCalendarAfterSelection: any;
   @Input('dropDownHorizontalAlignment') attrDropDownHorizontalAlignment: any;
   @Input('dropDownVerticalAlignment') attrDropDownVerticalAlignment: any;
   @Input('disabled') attrDisabled: any;
   @Input('enableBrowserBoundsDetection') attrEnableBrowserBoundsDetection: any;
   @Input('enableAbsoluteSelection') attrEnableAbsoluteSelection: any;
   @Input('firstDayOfWeek') attrFirstDayOfWeek: any;
   @Input('formatString') attrFormatString: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('openDelay') attrOpenDelay: any;
   @Input('placeHolder') attrPlaceHolder: any;
   @Input('popupZIndex') attrPopupZIndex: any;
   @Input('rtl') attrRtl: any;
   @Input('readonly') attrReadonly: any;
   @Input('showFooter') attrShowFooter: any;
   @Input('selectionMode') attrSelectionMode: any;
   @Input('showWeekNumbers') attrShowWeekNumbers: any;
   @Input('showTimeButton') attrShowTimeButton: any;
   @Input('showCalendarButton') attrShowCalendarButton: any;
   @Input('theme') attrTheme: any;
   @Input('template') attrTemplate: any;
   @Input('textAlign') attrTextAlign: any;
   @Input('todayString') attrTodayString: any;
   @Input('value') attrValue: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['animationType','allowNullDate','allowKeyboardDelete','clearString','culture','closeDelay','closeCalendarAfterSelection','dropDownHorizontalAlignment','dropDownVerticalAlignment','disabled','enableBrowserBoundsDetection','enableAbsoluteSelection','firstDayOfWeek','formatString','height','min','max','openDelay','placeHolder','popupZIndex','rtl','readonly','showFooter','selectionMode','showWeekNumbers','showTimeButton','showCalendarButton','theme','template','textAlign','todayString','value','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxDateTimeInput;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxDateTimeInput(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxDateTimeInput(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxDateTimeInput(this.properties[i])) {
                  this.host.jqxDateTimeInput(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxDateTimeInput', options);
      this.host = this.widgetObject['host'];
      this.__wireEvents__();
      this.__updateRect__();
      setTimeout(() => {
         options.value !== undefined ? this.host.jqxDateTimeInput('val', options.value) : this.host.jqxDateTimeInput('val', new Date());
      }, 1);
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   get ngValue(): any {
       if (this.widgetObject)
           return this.host.val();
       return '';
   }

   set ngValue(value: any) {
       if (this.widgetObject) {
           this.onChangeCallback(value);
       }
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.host.jqxDateTimeInput('val', value);
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxDateTimeInput('setOptions', options);
   }

   // jqxDateTimeInputComponent properties
   animationType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('animationType', arg);
      } else {
          return this.host.jqxDateTimeInput('animationType');
      }
   }

   allowNullDate(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('allowNullDate', arg);
      } else {
          return this.host.jqxDateTimeInput('allowNullDate');
      }
   }

   allowKeyboardDelete(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('allowKeyboardDelete', arg);
      } else {
          return this.host.jqxDateTimeInput('allowKeyboardDelete');
      }
   }

   clearString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('clearString', arg);
      } else {
          return this.host.jqxDateTimeInput('clearString');
      }
   }

   culture(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('culture', arg);
      } else {
          return this.host.jqxDateTimeInput('culture');
      }
   }

   closeDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('closeDelay', arg);
      } else {
          return this.host.jqxDateTimeInput('closeDelay');
      }
   }

   closeCalendarAfterSelection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('closeCalendarAfterSelection', arg);
      } else {
          return this.host.jqxDateTimeInput('closeCalendarAfterSelection');
      }
   }

   dropDownHorizontalAlignment(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('dropDownHorizontalAlignment', arg);
      } else {
          return this.host.jqxDateTimeInput('dropDownHorizontalAlignment');
      }
   }

   dropDownVerticalAlignment(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('dropDownVerticalAlignment', arg);
      } else {
          return this.host.jqxDateTimeInput('dropDownVerticalAlignment');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('disabled', arg);
      } else {
          return this.host.jqxDateTimeInput('disabled');
      }
   }

   enableBrowserBoundsDetection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('enableBrowserBoundsDetection', arg);
      } else {
          return this.host.jqxDateTimeInput('enableBrowserBoundsDetection');
      }
   }

   enableAbsoluteSelection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('enableAbsoluteSelection', arg);
      } else {
          return this.host.jqxDateTimeInput('enableAbsoluteSelection');
      }
   }

   firstDayOfWeek(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('firstDayOfWeek', arg);
      } else {
          return this.host.jqxDateTimeInput('firstDayOfWeek');
      }
   }

   formatString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('formatString', arg);
      } else {
          return this.host.jqxDateTimeInput('formatString');
      }
   }

   height(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('height', arg);
      } else {
          return this.host.jqxDateTimeInput('height');
      }
   }

   min(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('min', arg);
      } else {
          return this.host.jqxDateTimeInput('min');
      }
   }

   max(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('max', arg);
      } else {
          return this.host.jqxDateTimeInput('max');
      }
   }

   openDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('openDelay', arg);
      } else {
          return this.host.jqxDateTimeInput('openDelay');
      }
   }

   placeHolder(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('placeHolder', arg);
      } else {
          return this.host.jqxDateTimeInput('placeHolder');
      }
   }

   popupZIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('popupZIndex', arg);
      } else {
          return this.host.jqxDateTimeInput('popupZIndex');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('rtl', arg);
      } else {
          return this.host.jqxDateTimeInput('rtl');
      }
   }

   readonly(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('readonly', arg);
      } else {
          return this.host.jqxDateTimeInput('readonly');
      }
   }

   showFooter(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('showFooter', arg);
      } else {
          return this.host.jqxDateTimeInput('showFooter');
      }
   }

   selectionMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('selectionMode', arg);
      } else {
          return this.host.jqxDateTimeInput('selectionMode');
      }
   }

   showWeekNumbers(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('showWeekNumbers', arg);
      } else {
          return this.host.jqxDateTimeInput('showWeekNumbers');
      }
   }

   showTimeButton(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('showTimeButton', arg);
      } else {
          return this.host.jqxDateTimeInput('showTimeButton');
      }
   }

   showCalendarButton(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('showCalendarButton', arg);
      } else {
          return this.host.jqxDateTimeInput('showCalendarButton');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('theme', arg);
      } else {
          return this.host.jqxDateTimeInput('theme');
      }
   }

   template(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('template', arg);
      } else {
          return this.host.jqxDateTimeInput('template');
      }
   }

   textAlign(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('textAlign', arg);
      } else {
          return this.host.jqxDateTimeInput('textAlign');
      }
   }

   todayString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('todayString', arg);
      } else {
          return this.host.jqxDateTimeInput('todayString');
      }
   }

   value(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('value', arg);
      } else {
          return this.host.jqxDateTimeInput('value');
      }
   }

   width(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxDateTimeInput('width', arg);
      } else {
          return this.host.jqxDateTimeInput('width');
      }
   }


   // jqxDateTimeInputComponent functions
   close(): void {
      this.host.jqxDateTimeInput('close');
   }

   destroy(): void {
      this.host.jqxDateTimeInput('destroy');
   }

   focus(): void {
      this.host.jqxDateTimeInput('focus');
   }

   getRange(date: any): any {
      return this.host.jqxDateTimeInput('getRange', date);
   }

   getText(): string {
      return this.host.jqxDateTimeInput('getText');
   }

   getDate(): any {
      return this.host.jqxDateTimeInput('getDate');
   }

   getMaxDate(): any {
      return this.host.jqxDateTimeInput('getMaxDate');
   }

   getMinDate(): any {
      return this.host.jqxDateTimeInput('getMinDate');
   }

   open(): void {
      this.host.jqxDateTimeInput('open');
   }

   setRange(date: any, date2: any): void {
      this.host.jqxDateTimeInput('setRange', date, date2);
   }

   setMinDate(date: any): void {
      this.host.jqxDateTimeInput('setMinDate', date);
   }

   setMaxDate(date: any): void {
      this.host.jqxDateTimeInput('setMaxDate', date);
   }

   setDate(date: any): void {
      this.host.jqxDateTimeInput('setDate', date);
   }

   val(value, value2): any {
      if (value !== undefined) {
         this.host.jqxDateTimeInput("val", value, value2);
      } else {
         return this.host.jqxDateTimeInput("val");
      }
   };


   // jqxDateTimeInputComponent events
   @Output() onChange = new EventEmitter();
   @Output() onClose = new EventEmitter();
   @Output() onOpen = new EventEmitter();
   @Output() onTextchanged = new EventEmitter();
   @Output() onValueChanged = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); this.onChangeCallback(this.host.val()); });
      this.host.on('close', (eventData: any) => { this.onClose.emit(eventData); });
      this.host.on('open', (eventData: any) => { this.onOpen.emit(eventData); });
      this.host.on('textchanged', (eventData: any) => { this.onTextchanged.emit(eventData); });
      this.host.on('valueChanged', (eventData: any) => { this.onValueChanged.emit(eventData); this.onChangeCallback(this.host.val()); });
      this.host.on('keyup', () => { this.onChangeCallback(this.host.val()); });
   }

} //jqxDateTimeInputComponent
