// web/js/components/jqwidgets/jqwidgets-ts/angular_jqxchart.ts
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxChart',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxChartComponent implements OnChanges
{
   @Input('title') attrTitle: any;
   @Input('description') attrDescription: any;
   @Input('source') attrSource: any;
   @Input('showBorderLine') attrShowBorderLine: any;
   @Input('borderLineColor') attrBorderLineColor: any;
   @Input('borderLineWidth') attrBorderLineWidth: any;
   @Input('backgroundColor') attrBackgroundColor: any;
   @Input('backgroundImage') attrBackgroundImage: any;
   @Input('showLegend') attrShowLegend: any;
   @Input('legendLayout') attrLegendLayout: any;
   @Input('categoryAxis') attrCategoryAxis: any;
   @Input('padding') attrPadding: any;
   @Input('titlePadding') attrTitlePadding: any;
   @Input('colorScheme') attrColorScheme: any;
   @Input('greyScale') attrGreyScale: any;
   @Input('showToolTips') attrShowToolTips: any;
   @Input('toolTipShowDelay') attrToolTipShowDelay: any;
   @Input('toolTipHideDelay') attrToolTipHideDelay: any;
   @Input('toolTipMoveDuration') attrToolTipMoveDuration: any;
   @Input('drawBefore') attrDrawBefore: any;
   @Input('draw') attrDraw: any;
   @Input('rtl') attrRtl: any;
   @Input('enableCrosshairs') attrEnableCrosshairs: any;
   @Input('crosshairsColor') attrCrosshairsColor: any;
   @Input('crosshairsDashStyle') attrCrosshairsDashStyle: any;
   @Input('crosshairsLineWidth') attrCrosshairsLineWidth: any;
   @Input('columnSeriesOverlap') attrColumnSeriesOverlap: any;
   @Input('enabled') attrEnabled: any;
   @Input('enableAnimations') attrEnableAnimations: any;
   @Input('animationDuration') attrAnimationDuration: any;
   @Input('enableAxisTextAnimation') attrEnableAxisTextAnimation: any;
   @Input('renderEngine') attrRenderEngine: any;
   @Input('xAxis') attrXAxis: any;
   @Input('valueAxis') attrValueAxis: any;
   @Input('seriesGroups') attrSeriesGroups: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['title','description','source','showBorderLine','borderLineColor','borderLineWidth','backgroundColor','backgroundImage','showLegend','legendLayout','categoryAxis','padding','titlePadding','colorScheme','greyScale','showToolTips','toolTipShowDelay','toolTipHideDelay','toolTipMoveDuration','drawBefore','draw','rtl','enableCrosshairs','crosshairsColor','crosshairsDashStyle','crosshairsLineWidth','columnSeriesOverlap','enabled','enableAnimations','animationDuration','enableAxisTextAnimation','renderEngine','xAxis','valueAxis','seriesGroups'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxChart;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
      window.onresize = () => {
          this.__updateRect__();
      };
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         if (changes.hasOwnProperty('attrWidth') || changes.hasOwnProperty('attrHeight')) {
            this.__updateRect__();
         }
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxChart(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxChart(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxChart(this.properties[i])) {
                  this.host.jqxChart(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxChart', options);
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
      this.refresh();
   }

   setOptions(options: any) : void {
      this.host.jqxChart('setOptions', options);
   }

   // jqxChartComponent properties
   title(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('title', arg);
      } else {
          return this.host.jqxChart('title');
      }
   }

   description(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('description', arg);
      } else {
          return this.host.jqxChart('description');
      }
   }

   source(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxChart('source', arg);
      } else {
          return this.host.jqxChart('source');
      }
   }

   showBorderLine(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('showBorderLine', arg);
      } else {
          return this.host.jqxChart('showBorderLine');
      }
   }

   borderLineColor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('borderLineColor', arg);
      } else {
          return this.host.jqxChart('borderLineColor');
      }
   }

   borderLineWidth(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxChart('borderLineWidth', arg);
      } else {
          return this.host.jqxChart('borderLineWidth');
      }
   }

   backgroundColor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('backgroundColor', arg);
      } else {
          return this.host.jqxChart('backgroundColor');
      }
   }

   backgroundImage(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('backgroundImage', arg);
      } else {
          return this.host.jqxChart('backgroundImage');
      }
   }

   showLegend(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('showLegend', arg);
      } else {
          return this.host.jqxChart('showLegend');
      }
   }

   legendLayout(arg?: jqwidgets.ChartLegendLayout) : any {
      if (arg !== undefined) {
          this.host.jqxChart('legendLayout', arg);
      } else {
          return this.host.jqxChart('legendLayout');
      }
   }

   categoryAxis(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxChart('categoryAxis', arg);
      } else {
          return this.host.jqxChart('categoryAxis');
      }
   }

   padding(arg?: jqwidgets.ChartPadding) : any {
      if (arg !== undefined) {
          this.host.jqxChart('padding', arg);
      } else {
          return this.host.jqxChart('padding');
      }
   }

   titlePadding(arg?: jqwidgets.ChartPadding) : any {
      if (arg !== undefined) {
          this.host.jqxChart('titlePadding', arg);
      } else {
          return this.host.jqxChart('titlePadding');
      }
   }

   colorScheme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('colorScheme', arg);
      } else {
          return this.host.jqxChart('colorScheme');
      }
   }

   greyScale(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('greyScale', arg);
      } else {
          return this.host.jqxChart('greyScale');
      }
   }

   showToolTips(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('showToolTips', arg);
      } else {
          return this.host.jqxChart('showToolTips');
      }
   }

   toolTipShowDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxChart('toolTipShowDelay', arg);
      } else {
          return this.host.jqxChart('toolTipShowDelay');
      }
   }

   toolTipHideDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxChart('toolTipHideDelay', arg);
      } else {
          return this.host.jqxChart('toolTipHideDelay');
      }
   }

   toolTipMoveDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxChart('toolTipMoveDuration', arg);
      } else {
          return this.host.jqxChart('toolTipMoveDuration');
      }
   }

   drawBefore(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxChart('drawBefore', arg);
      } else {
          return this.host.jqxChart('drawBefore');
      }
   }

   draw(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxChart('draw', arg);
      } else {
          return this.host.jqxChart('draw');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('rtl', arg);
      } else {
          return this.host.jqxChart('rtl');
      }
   }

   enableCrosshairs(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('enableCrosshairs', arg);
      } else {
          return this.host.jqxChart('enableCrosshairs');
      }
   }

   crosshairsColor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('crosshairsColor', arg);
      } else {
          return this.host.jqxChart('crosshairsColor');
      }
   }

   crosshairsDashStyle(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('crosshairsDashStyle', arg);
      } else {
          return this.host.jqxChart('crosshairsDashStyle');
      }
   }

   crosshairsLineWidth(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxChart('crosshairsLineWidth', arg);
      } else {
          return this.host.jqxChart('crosshairsLineWidth');
      }
   }

   columnSeriesOverlap(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('columnSeriesOverlap', arg);
      } else {
          return this.host.jqxChart('columnSeriesOverlap');
      }
   }

   enabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('enabled', arg);
      } else {
          return this.host.jqxChart('enabled');
      }
   }

   enableAnimations(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('enableAnimations', arg);
      } else {
          return this.host.jqxChart('enableAnimations');
      }
   }

   animationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxChart('animationDuration', arg);
      } else {
          return this.host.jqxChart('animationDuration');
      }
   }

   enableAxisTextAnimation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxChart('enableAxisTextAnimation', arg);
      } else {
          return this.host.jqxChart('enableAxisTextAnimation');
      }
   }

   renderEngine(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxChart('renderEngine', arg);
      } else {
          return this.host.jqxChart('renderEngine');
      }
   }

   xAxis(arg?: jqwidgets.ChartXAxis) : any {
      if (arg !== undefined) {
          this.host.jqxChart('xAxis', arg);
      } else {
          return this.host.jqxChart('xAxis');
      }
   }

   valueAxis(arg?: jqwidgets.ChartValueAxis) : any {
      if (arg !== undefined) {
          this.host.jqxChart('valueAxis', arg);
      } else {
          return this.host.jqxChart('valueAxis');
      }
   }

   seriesGroups(arg?: Array<jqwidgets.ChartSeriesGroup>) : any {
      if (arg !== undefined) {
          this.host.jqxChart('seriesGroups', arg);
      } else {
          return this.host.jqxChart('seriesGroups');
      }
   }


   // jqxChartComponent functions
   getInstance(): any {
      return this.host.jqxChart('getInstance');
   }

   refresh(): void {
      this.host.jqxChart('refresh');
   }

   update(): void {
      this.host.jqxChart('update');
   }

   destroy(): void {
      this.host.jqxChart('destroy');
   }

   addColorScheme(schemeName: string, colors: Array<string>): void {
      this.host.jqxChart('addColorScheme', schemeName, colors);
   }

   removeColorScheme(schemeName: string): void {
      this.host.jqxChart('removeColorScheme', schemeName);
   }

   getItemsCount(groupIndex: number, serieIndex: number): number {
      return this.host.jqxChart('getItemsCount', groupIndex, serieIndex);
   }

   getItemCoord(groupIndex: number, serieIndex: number, itemIndex: number): any {
      return this.host.jqxChart('getItemCoord', groupIndex, serieIndex, itemIndex);
   }

   getXAxisRect(groupIndex: number): jqwidgets.ChartRect {
      return this.host.jqxChart('getXAxisRect', groupIndex);
   }

   getXAxisLabels(groupIndex: number): Array<any> {
      return this.host.jqxChart('getXAxisLabels', groupIndex);
   }

   getValueAxisRect(groupIndex: number): jqwidgets.ChartRect {
      return this.host.jqxChart('getValueAxisRect', groupIndex);
   }

   getValueAxisLabels(groupIndex: number): Array<any> {
      return this.host.jqxChart('getValueAxisLabels', groupIndex);
   }

   getColorScheme(colorScheme: string): Array<string> {
      return this.host.jqxChart('getColorScheme', colorScheme);
   }

   hideSerie(groupIndex: number, serieIndex: number, itemIndex: number): void {
      this.host.jqxChart('hideSerie', groupIndex, serieIndex, itemIndex);
   }

   showSerie(groupIndex: number, serieIndex: number, itemIndex: number): void {
      this.host.jqxChart('showSerie', groupIndex, serieIndex, itemIndex);
   }

   hideToolTip(hideDelay: number): void {
      this.host.jqxChart('hideToolTip', hideDelay);
   }

   showToolTip(groupIndex: number, serieIndex: number, itemIndex: number, showDelay: number, hideDelay: number): void {
      this.host.jqxChart('showToolTip', groupIndex, serieIndex, itemIndex, showDelay, hideDelay);
   }

   saveAsJPEG(fileName: string, exportServerUrl: string): void {
      this.host.jqxChart('saveAsJPEG', fileName, exportServerUrl);
   }

   saveAsPNG(fileName: string, exportServerUrl: string): void {
      this.host.jqxChart('saveAsPNG', fileName, exportServerUrl);
   }

   saveAsPDF(fileName: string, exportServerUrl: string): void {
      this.host.jqxChart('saveAsPDF', fileName, exportServerUrl);
   }

   getXAxisValue(offset: number, groupIndex: number): any {
      return this.host.jqxChart('getXAxisValue', offset, groupIndex);
   }

   getValueAxisValue(offset: number, groupIndex: number): any {
      return this.host.jqxChart('getValueAxisValue', offset, groupIndex);
   }


   // jqxChartComponent events
   @Output() onToggle = new EventEmitter();
   @Output() onClick = new EventEmitter();
   @Output() onMouseOver = new EventEmitter();
   @Output() onMouseOut = new EventEmitter();
   @Output() onRefreshBegin = new EventEmitter();
   @Output() onRefreshEnd = new EventEmitter();
   @Output() onRangeSelectionChanging = new EventEmitter();
   @Output() onRangeSelectionChanged = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('toggle', (eventData: any) => { this.onToggle.emit(eventData); });
      this.host.on('click', (eventData: any) => { this.onClick.emit(eventData); });
      this.host.on('mouseOver', (eventData: any) => { this.onMouseOver.emit(eventData); });
      this.host.on('mouseOut', (eventData: any) => { this.onMouseOut.emit(eventData); });
      this.host.on('refreshBegin', (eventData: any) => { this.onRefreshBegin.emit(eventData); });
      this.host.on('refreshEnd', (eventData: any) => { this.onRefreshEnd.emit(eventData); });
      this.host.on('rangeSelectionChanging', (eventData: any) => { this.onRangeSelectionChanging.emit(eventData); });
      this.host.on('rangeSelectionChanged', (eventData: any) => { this.onRangeSelectionChanged.emit(eventData); });
   }

} //jqxChartComponent

// web/js/components/jqwidgets/jqwidgets-react/react_jqxchart.js
/*
jQWidgets v4.5.4 (2017-June)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

const JQXLite = window.JQXLite;

export default class JqxChart extends React.Component {
    componentDidMount() {
        let options = this.manageAttributes();
        this.createComponent(options);
    };
    manageAttributes() {
        let properties = ['title','description','source','showBorderLine','borderLineColor','borderLineWidth','backgroundColor','backgroundImage','showLegend','legendLayout','categoryAxis','padding','titlePadding','colorScheme','greyScale','showToolTips','toolTipShowDelay','toolTipHideDelay','toolTipMoveDuration','drawBefore','draw','rtl','enableCrosshairs','crosshairsColor','crosshairsDashStyle','crosshairsLineWidth','columnSeriesOverlap','enabled','enableAnimations','animationDuration','enableAxisTextAnimation','renderEngine','xAxis','valueAxis','seriesGroups'];
        let options = {};
        for(let item in this.props) {
              if(item === 'settings') {
                  for(let itemTwo in this.props[item]) {
                      options[itemTwo] = this.props[item][itemTwo];
                      }
                } else {
                      if(properties.indexOf(item) !== -1) {
                        options[item] = this.props[item];
                      }
                }
          }
          return options;
      };
    createComponent(options) {
        if(!this.style) {
              for (let style in this.props.style) {
                  JQXLite(this.componentSelector).css(style, this.props.style[style]);
              }
        }
        if(this.props.className !== undefined) {
            let classes = this.props.className.split(' ');
            for (let i = 0; i < classes.length; i++ ) {
                JQXLite(this.componentSelector).addClass(classes[i]);
            }
        }
        if(!this.template) {
              JQXLite(this.componentSelector).html(this.props.template);
        }
        JQXLite(this.componentSelector).jqxChart(options);
    };
    setOptions(options) {
        JQXLite(this.componentSelector).jqxChart('setOptions', options);
    };
    getOptions() {
        if(arguments.length === 0) {
            throw Error('At least one argument expected in getOptions()!');
        }
        let resultToReturn = {};
        for(let i = 0; i < arguments.length; i++) {
            resultToReturn[arguments[i]] = JQXLite(this.componentSelector).jqxChart(arguments[i]);
        }
        return resultToReturn;
    };
    on(name,callbackFn) {
        JQXLite(this.componentSelector).on(name,callbackFn);
    };
    off(name) {
        JQXLite(this.componentSelector).off(name);
    };
    title(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('title', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('title');
        }
    };
    description(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('description', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('description');
        }
    };
    source(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('source', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('source');
        }
    };
    showBorderLine(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('showBorderLine', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('showBorderLine');
        }
    };
    borderLineColor(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('borderLineColor', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('borderLineColor');
        }
    };
    borderLineWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('borderLineWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('borderLineWidth');
        }
    };
    backgroundColor(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('backgroundColor', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('backgroundColor');
        }
    };
    backgroundImage(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('backgroundImage', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('backgroundImage');
        }
    };
    showLegend(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('showLegend', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('showLegend');
        }
    };
    legendLayout(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('legendLayout', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('legendLayout');
        }
    };
    categoryAxis(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('categoryAxis', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('categoryAxis');
        }
    };
    padding(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('padding', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('padding');
        }
    };
    titlePadding(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('titlePadding', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('titlePadding');
        }
    };
    colorScheme(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('colorScheme', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('colorScheme');
        }
    };
    greyScale(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('greyScale', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('greyScale');
        }
    };
    showToolTips(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('showToolTips', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('showToolTips');
        }
    };
    toolTipShowDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('toolTipShowDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('toolTipShowDelay');
        }
    };
    toolTipHideDelay(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('toolTipHideDelay', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('toolTipHideDelay');
        }
    };
    toolTipMoveDuration(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('toolTipMoveDuration', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('toolTipMoveDuration');
        }
    };
    drawBefore(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('drawBefore', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('drawBefore');
        }
    };
    draw(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('draw', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('draw');
        }
    };
    rtl(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('rtl', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('rtl');
        }
    };
    enableCrosshairs(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('enableCrosshairs', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('enableCrosshairs');
        }
    };
    crosshairsColor(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('crosshairsColor', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('crosshairsColor');
        }
    };
    crosshairsDashStyle(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('crosshairsDashStyle', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('crosshairsDashStyle');
        }
    };
    crosshairsLineWidth(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('crosshairsLineWidth', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('crosshairsLineWidth');
        }
    };
    columnSeriesOverlap(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('columnSeriesOverlap', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('columnSeriesOverlap');
        }
    };
    enabled(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('enabled', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('enabled');
        }
    };
    enableAnimations(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('enableAnimations', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('enableAnimations');
        }
    };
    animationDuration(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('animationDuration', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('animationDuration');
        }
    };
    enableAxisTextAnimation(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('enableAxisTextAnimation', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('enableAxisTextAnimation');
        }
    };
    renderEngine(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('renderEngine', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('renderEngine');
        }
    };
    xAxis(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('xAxis', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('xAxis');
        }
    };
    valueAxis(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('valueAxis', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('valueAxis');
        }
    };
    seriesGroups(arg) {
        if (arg !== undefined) {
            JQXLite(this.componentSelector).jqxChart('seriesGroups', arg)
        } else {
            return JQXLite(this.componentSelector).jqxChart('seriesGroups');
        }
    };
    getInstance() {
        return JQXLite(this.componentSelector).jqxChart('getInstance');  
    };
    refresh() {
        return JQXLite(this.componentSelector).jqxChart('refresh');  
    };
    update() {
        return JQXLite(this.componentSelector).jqxChart('update');  
    };
    destroy() {
        return JQXLite(this.componentSelector).jqxChart('destroy');  
    };
    addColorScheme(schemeName, colors) {
        return JQXLite(this.componentSelector).jqxChart('addColorScheme', schemeName, colors);  
    };
    removeColorScheme(schemeName) {
        return JQXLite(this.componentSelector).jqxChart('removeColorScheme', schemeName);  
    };
    getItemsCount(groupIndex, serieIndex) {
        return JQXLite(this.componentSelector).jqxChart('getItemsCount', groupIndex, serieIndex);  
    };
    getItemCoord(groupIndex, serieIndex, itemIndex) {
        return JQXLite(this.componentSelector).jqxChart('getItemCoord', groupIndex, serieIndex, itemIndex);  
    };
    getXAxisRect(groupIndex) {
        return JQXLite(this.componentSelector).jqxChart('getXAxisRect', groupIndex);  
    };
    getXAxisLabels(groupIndex) {
        return JQXLite(this.componentSelector).jqxChart('getXAxisLabels', groupIndex);  
    };
    getValueAxisRect(groupIndex) {
        return JQXLite(this.componentSelector).jqxChart('getValueAxisRect', groupIndex);  
    };
    getValueAxisLabels(groupIndex) {
        return JQXLite(this.componentSelector).jqxChart('getValueAxisLabels', groupIndex);  
    };
    getColorScheme(colorScheme) {
        return JQXLite(this.componentSelector).jqxChart('getColorScheme', colorScheme);  
    };
    hideSerie(groupIndex, serieIndex, itemIndex) {
        return JQXLite(this.componentSelector).jqxChart('hideSerie', groupIndex, serieIndex, itemIndex);  
    };
    showSerie(groupIndex, serieIndex, itemIndex) {
        return JQXLite(this.componentSelector).jqxChart('showSerie', groupIndex, serieIndex, itemIndex);  
    };
    hideToolTip(hideDelay) {
        return JQXLite(this.componentSelector).jqxChart('hideToolTip', hideDelay);  
    };
    showToolTip(groupIndex, serieIndex, itemIndex, showDelay, hideDelay) {
        return JQXLite(this.componentSelector).jqxChart('showToolTip', groupIndex, serieIndex, itemIndex, showDelay, hideDelay);  
    };
    saveAsJPEG(fileName, exportServerUrl) {
        return JQXLite(this.componentSelector).jqxChart('saveAsJPEG', fileName, exportServerUrl);  
    };
    saveAsPNG(fileName, exportServerUrl) {
        return JQXLite(this.componentSelector).jqxChart('saveAsPNG', fileName, exportServerUrl);  
    };
    saveAsPDF(fileName, exportServerUrl) {
        return JQXLite(this.componentSelector).jqxChart('saveAsPDF', fileName, exportServerUrl);  
    };
    getXAxisValue(offset, groupIndex) {
        return JQXLite(this.componentSelector).jqxChart('getXAxisValue', offset, groupIndex);  
    };
    getValueAxisValue(offset, groupIndex) {
        return JQXLite(this.componentSelector).jqxChart('getValueAxisValue', offset, groupIndex);  
    };
    render() {
        let id = 'jqxChart' + JQXLite.generateID();
        this.componentSelector = '#' + id;
        return (
            <div id={id}>{this.props.value}{this.props.children}</div>
        )
    };
};
