// web/js/components/jqwidgets/jqwidgets-ts/angular_jqxfileupload.ts
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxFileUpload',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxFileUploadComponent implements OnChanges
{
   @Input('autoUpload') attrAutoUpload: any;
   @Input('accept') attrAccept: any;
   @Input('browseTemplate') attrBrowseTemplate: any;
   @Input('cancelTemplate') attrCancelTemplate: any;
   @Input('disabled') attrDisabled: any;
   @Input('fileInputName') attrFileInputName: any;
   @Input('localization') attrLocalization: any;
   @Input('multipleFilesUpload') attrMultipleFilesUpload: any;
   @Input('renderFiles') attrRenderFiles: any;
   @Input('rtl') attrRtl: any;
   @Input('theme') attrTheme: any;
   @Input('uploadUrl') attrUploadUrl: any;
   @Input('uploadTemplate') attrUploadTemplate: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['autoUpload','accept','browseTemplate','cancelTemplate','disabled','fileInputName','height','localization','multipleFilesUpload','renderFiles','rtl','theme','uploadUrl','uploadTemplate','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxFileUpload;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxFileUpload(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxFileUpload(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxFileUpload(this.properties[i])) {
                  this.host.jqxFileUpload(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxFileUpload', options);
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxFileUpload('setOptions', options);
   }

   // jqxFileUploadComponent properties
   autoUpload(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('autoUpload', arg);
      } else {
          return this.host.jqxFileUpload('autoUpload');
      }
   }

   accept(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('accept', arg);
      } else {
          return this.host.jqxFileUpload('accept');
      }
   }

   browseTemplate(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('browseTemplate', arg);
      } else {
          return this.host.jqxFileUpload('browseTemplate');
      }
   }

   cancelTemplate(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('cancelTemplate', arg);
      } else {
          return this.host.jqxFileUpload('cancelTemplate');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('disabled', arg);
      } else {
          return this.host.jqxFileUpload('disabled');
      }
   }

   fileInputName(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('fileInputName', arg);
      } else {
          return this.host.jqxFileUpload('fileInputName');
      }
   }

   height(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('height', arg);
      } else {
          return this.host.jqxFileUpload('height');
      }
   }

   localization(arg?: jqwidgets.FileUploadLocalization) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('localization', arg);
      } else {
          return this.host.jqxFileUpload('localization');
      }
   }

   multipleFilesUpload(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('multipleFilesUpload', arg);
      } else {
          return this.host.jqxFileUpload('multipleFilesUpload');
      }
   }

   renderFiles(arg?: (filename:any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('renderFiles', arg);
      } else {
          return this.host.jqxFileUpload('renderFiles');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('rtl', arg);
      } else {
          return this.host.jqxFileUpload('rtl');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('theme', arg);
      } else {
          return this.host.jqxFileUpload('theme');
      }
   }

   uploadUrl(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('uploadUrl', arg);
      } else {
          return this.host.jqxFileUpload('uploadUrl');
      }
   }

   uploadTemplate(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('uploadTemplate', arg);
      } else {
          return this.host.jqxFileUpload('uploadTemplate');
      }
   }

   width(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxFileUpload('width', arg);
      } else {
          return this.host.jqxFileUpload('width');
      }
   }


   // jqxFileUploadComponent functions
   browse(): void {
      this.host.jqxFileUpload('browse');
   }

   cancelFile(): void {
      this.host.jqxFileUpload('cancelFile');
   }

   cancelAll(): void {
      this.host.jqxFileUpload('cancelAll');
   }

   destroy(): void {
      this.host.jqxFileUpload('destroy');
   }

   render(): void {
      this.host.jqxFileUpload('render');
   }

   refresh(): void {
      this.host.jqxFileUpload('refresh');
   }

   uploadFile(fileIndex: number): void {
      this.host.jqxFileUpload('uploadFile', fileIndex);
   }

   uploadAll(): void {
      this.host.jqxFileUpload('uploadAll');
   }


   // jqxFileUploadComponent events
   @Output() onRemove = new EventEmitter();
   @Output() onSelect = new EventEmitter();
   @Output() onUploadStart = new EventEmitter();
   @Output() onUploadEnd = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('remove', (eventData: any) => { this.onRemove.emit(eventData); });
      this.host.on('select', (eventData: any) => { this.onSelect.emit(eventData); });
      this.host.on('uploadStart', (eventData: any) => { this.onUploadStart.emit(eventData); });
      this.host.on('uploadEnd', (eventData: any) => { this.onUploadEnd.emit(eventData); });
   }

} //jqxFileUploadComponent

// web/js/components/jqwidgets/jqwidgets-react/react_jqxfileupload.js
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxFileUpload = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['autoUpload','accept','browseTemplate','cancelTemplate','disabled','fileInputName','height','localization','multipleFilesUpload','renderFiles','rtl','theme','uploadUrl','uploadTemplate','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxFileUpload(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxFileUpload('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxFileUpload(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  autoUpload: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("autoUpload", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("autoUpload");
    }
  },
  accept: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("accept", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("accept");
    }
  },
  browseTemplate: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("browseTemplate", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("browseTemplate");
    }
  },
  cancelTemplate: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("cancelTemplate", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("cancelTemplate");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("disabled");
    }
  },
  fileInputName: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("fileInputName", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("fileInputName");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("height");
    }
  },
  localization: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("localization", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("localization");
    }
  },
  multipleFilesUpload: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("multipleFilesUpload", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("multipleFilesUpload");
    }
  },
  renderFiles: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("renderFiles", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("renderFiles");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("rtl");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("theme");
    }
  },
  uploadUrl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("uploadUrl", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("uploadUrl");
    }
  },
  uploadTemplate: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("uploadTemplate", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("uploadTemplate");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxFileUpload("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxFileUpload("width");
    }
  },
  browse: function () {
    $("#" + this.componentSelector).jqxFileUpload("browse");  
  },
  cancelFile: function () {
    $("#" + this.componentSelector).jqxFileUpload("cancelFile");  
  },
  cancelAll: function () {
    $("#" + this.componentSelector).jqxFileUpload("cancelAll");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxFileUpload("destroy");  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxFileUpload("render");
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxFileUpload("refresh");  
  },
  uploadFile: function (fileIndex) {
    $("#" + this.componentSelector).jqxFileUpload("uploadFile", fileIndex);  
  },
  uploadAll: function () {
    $("#" + this.componentSelector).jqxFileUpload("uploadAll");  
  },
  render: function () {
    var id = 'jqxFileUpload' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxFileUpload;
