// web/js/components/jqwidgets/jqwidgets-ts/angular_jqxbulletchart.ts
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxBulletChart',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxBulletChartComponent implements OnChanges
{
   @Input('animationDuration') attrAnimationDuration: any;
   @Input('barSize') attrBarSize: any;
   @Input('description') attrDescription: any;
   @Input('disabled') attrDisabled: any;
   @Input('labelsFormat') attrLabelsFormat: any;
   @Input('labelsFormatFunction') attrLabelsFormatFunction: any;
   @Input('orientation') attrOrientation: any;
   @Input('pointer') attrPointer: any;
   @Input('rtl') attrRtl: any;
   @Input('ranges') attrRanges: any;
   @Input('showTooltip') attrShowTooltip: any;
   @Input('target') attrTarget: any;
   @Input('ticks') attrTicks: any;
   @Input('title') attrTitle: any;
   @Input('tooltipFormatFunction') attrTooltipFormatFunction: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['animationDuration','barSize','description','disabled','height','labelsFormat','labelsFormatFunction','orientation','pointer','rtl','ranges','showTooltip','target','ticks','title','tooltipFormatFunction','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxBulletChart;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
      setTimeout(() => {
         if (this.autoCreate) {
            this.createComponent(); 
         }
      }); 
   }

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName]) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxBulletChart(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxBulletChart(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxBulletChart(this.properties[i])) {
                  this.host.jqxBulletChart(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }
   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxBulletChart', options);
      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxBulletChart('setOptions', options);
   }

   // jqxBulletChartComponent properties
   animationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('animationDuration', arg);
      } else {
          return this.host.jqxBulletChart('animationDuration');
      }
   }

   barSize(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('barSize', arg);
      } else {
          return this.host.jqxBulletChart('barSize');
      }
   }

   description(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('description', arg);
      } else {
          return this.host.jqxBulletChart('description');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('disabled', arg);
      } else {
          return this.host.jqxBulletChart('disabled');
      }
   }

   height(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('height', arg);
      } else {
          return this.host.jqxBulletChart('height');
      }
   }

   labelsFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('labelsFormat', arg);
      } else {
          return this.host.jqxBulletChart('labelsFormat');
      }
   }

   labelsFormatFunction(arg?: (value?: number, position?:string ) => any) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('labelsFormatFunction', arg);
      } else {
          return this.host.jqxBulletChart('labelsFormatFunction');
      }
   }

   orientation(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('orientation', arg);
      } else {
          return this.host.jqxBulletChart('orientation');
      }
   }

   pointer(arg?: jqwidgets.BulletChartPointer) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('pointer', arg);
      } else {
          return this.host.jqxBulletChart('pointer');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('rtl', arg);
      } else {
          return this.host.jqxBulletChart('rtl');
      }
   }

   ranges(arg?: Array<jqwidgets.BulletChartRanges>) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('ranges', arg);
      } else {
          return this.host.jqxBulletChart('ranges');
      }
   }

   showTooltip(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('showTooltip', arg);
      } else {
          return this.host.jqxBulletChart('showTooltip');
      }
   }

   target(arg?: jqwidgets.BulletChartPointer) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('target', arg);
      } else {
          return this.host.jqxBulletChart('target');
      }
   }

   ticks(arg?: jqwidgets.BulletChartTicks) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('ticks', arg);
      } else {
          return this.host.jqxBulletChart('ticks');
      }
   }

   title(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('title', arg);
      } else {
          return this.host.jqxBulletChart('title');
      }
   }

   tooltipFormatFunction(arg?: (pointerValue:number , targetValue:number) => String) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('tooltipFormatFunction', arg);
      } else {
          return this.host.jqxBulletChart('tooltipFormatFunction');
      }
   }

   width(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxBulletChart('width', arg);
      } else {
          return this.host.jqxBulletChart('width');
      }
   }


   // jqxBulletChartComponent functions
   destroy(): void {
      this.host.jqxBulletChart('destroy');
   }

   render(): void {
      this.host.jqxBulletChart('render');
   }

   refresh(): void {
      this.host.jqxBulletChart('refresh');
   }

   val(value): any {
      if (value !== undefined) {
         this.host.jqxBulletChart("val", value);
      } else {
         return this.host.jqxBulletChart("val");
      }
   };


   // jqxBulletChartComponent events
   @Output() onChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); });
   }

} //jqxBulletChartComponent

// web/js/components/jqwidgets/jqwidgets-react/react_jqxbulletchart.js
/*
jQWidgets v4.5.1 (2017-April)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxBulletChart = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['animationDuration','barSize','description','disabled','height','labelsFormat','labelsFormatFunction','orientation','pointer','rtl','ranges','showTooltip','target','ticks','title','tooltipFormatFunction','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxBulletChart(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxBulletChart('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxBulletChart(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  animationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("animationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("animationDuration");
    }
  },
  barSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("barSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("barSize");
    }
  },
  description: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("description", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("description");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("disabled");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("height");
    }
  },
  labelsFormat: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("labelsFormat", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("labelsFormat");
    }
  },
  labelsFormatFunction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("labelsFormatFunction", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("labelsFormatFunction");
    }
  },
  orientation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("orientation", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("orientation");
    }
  },
  pointer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("pointer", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("pointer");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("rtl");
    }
  },
  ranges: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("ranges", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("ranges");
    }
  },
  showTooltip: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("showTooltip", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("showTooltip");
    }
  },
  target: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("target", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("target");
    }
  },
  ticks: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("ticks", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("ticks");
    }
  },
  title: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("title", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("title");
    }
  },
  tooltipFormatFunction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("tooltipFormatFunction", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("tooltipFormatFunction");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxBulletChart("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxBulletChart("width");
    }
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxBulletChart("destroy");  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxBulletChart("render");
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxBulletChart("refresh");  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxBulletChart("val", value)
    } else {
      return $("#" + this.componentSelector).jqxBulletChart("val");
    }
  },

  render: function () {
    var id = 'jqxBulletChart' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxBulletChart;
